version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: database
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'YES'
        networks:
            - symfony

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - symfony

    # Symfony apache project container
    symfony:
        build: docker/php
        container_name: symfony
        ports:
          - "8000:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - symfony

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - symfony

networks:
    symfony:

volumes:
    db-data: